@model System.Web.Mvc.HandleErrorInfo
 @{
        Layout = "~/Views/Shared/_layout.cshtml";
    }
    
    <div id="page-loaderR"><span class="loaderR"><span class="loader-innerR">S</span></span></div>

    <!-- Container di Pagina -->

    <div id="page-container" class="sidebar-l sidebar-mini sidebar-o header-navbar-fixed">

        @Html.Partial("../Shared/sidebar",myRaiHelper.UtenteHelper.getSidebarModel())

        @Html.Partial("../Shared/header")
        <main id="main-container" style="min-height: 444px;">
				<div class="content bg-white text-center pulldown overflow-hidden">
						<div class="row">

                        <div class="col-sm-6 col-sm-offset-3">
                            <i class="font-s128 font-w300 push-50 text-danger animated bounceInDown h1 di di-error fa-2x"></i>
                             <h2 class="h3 font-w300 push-50 animated fadeInUp">Siamo spiacenti ma si è verificato un problema non previsto....</h2>
                             <h4 class="h4 font-w300 push-50"> @if (Session["idError"] != null)
                                                               {  @Session["idError"].ToString()}
                                 @if (Model != null)
                                 { @Model.Exception.Message}</h4>
                            @if (Model != null)
                            {
                                 @(Model.ActionName) @Html.Label("/") @(Model.ControllerName)
                            }
                         </div>


						
                        @*@Model.Exception.InnerException*@

					</div>
                    @*@Model.Exception.StackTrace*@
				</div>
			</main>
    </div>
